version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job with the type << pipeline.trigger_parameters.circleci.event_type >>"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job in the branch one"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test